name: MyPlugin
version: '${version}'
main: ru.ritefreak.myplugin.MyPlugin
depend:
  - Vault
api-version: '1.16'

commands:
  gm:
    description: change game mode
    aliases:
      - gamemode

  heal:
    description: heal you!
